// Generated by https://quicktype.io

export interface Directions {
    routes:    Route[];
    waypoints: Waypoint[];
    code:      string;
    uuid:      string;
}

export interface Route {
    country_crossed:  boolean;
    weight_typical:   number;
    duration_typical: number;
    weight_name:      string;
    weight:           number;
    duration:         number;
    distance:         number;
    legs:             Leg[];
    geometry:         Geometry;
}

export interface Geometry {
    coordinates: Array<number[]>;
    type:        Type;
}

export enum Type {
    LineString = "LineString",
}

export interface Leg {
    via_waypoints:    any[];
    admins:           Admin[];
    weight_typical:   number;
    duration_typical: number;
    weight:           number;
    duration:         number;
    steps:            Step[];
    distance:         number;
    summary:          string;
}

export interface Admin {
    iso_3166_1_alpha3: string;
    iso_3166_1:        string;
}

export interface Step {
    intersections:    Intersection[];
    maneuver:         Maneuver;
    name:             string;
    weight_typical:   number;
    duration_typical: number;
    duration:         number;
    distance:         number;
    driving_side:     DrivingSide;
    weight:           number;
    mode:             Mode;
    geometry:         Geometry;
    destinations?:    string;
    ref?:             string;
    exits?:           string;
}

export enum DrivingSide {
    Left = "left",
    Right = "right",
    SlightLeft = "slight left",
    SlightRight = "slight right",
    Straight = "straight",
}

export interface Intersection {
    entry:              boolean[];
    bearings:           number[];
    duration?:          number;
    traffic_signal?:    boolean;
    mapbox_streets_v8?: MapboxStreetsV8;
    is_urban?:          boolean;
    admin_index:        number;
    out?:               number;
    weight?:            number;
    geometry_index:     number;
    location:           number[];
    in?:                number;
    turn_weight?:       number;
    turn_duration?:     number;
    classes?:           ClassElement[];
    lanes?:             Lane[];
    toll_collection?:   TollCollection;
    railway_crossing?:  boolean;
}

export enum ClassElement {
    Motorway = "motorway",
    Tunnel = "tunnel",
}

export interface Lane {
    indications:       DrivingSide[];
    valid:             boolean;
    active:            boolean;
    valid_indication?: DrivingSide;
}

export interface MapboxStreetsV8 {
    class: MapboxStreetsV8Class;
}

export enum MapboxStreetsV8Class {
    Motorway = "motorway",
    MotorwayLink = "motorway_link",
    Primary = "primary",
    PrimaryLink = "primary_link",
    Secondary = "secondary",
    SecondaryLink = "secondary_link",
    Service = "service",
    Street = "street",
    Tertiary = "tertiary",
    TertiaryLink = "tertiary_link",
    Trunk = "trunk",
}

export interface TollCollection {
    name: string;
    type: string;
}

export interface Maneuver {
    type:           string;
    instruction:    string;
    bearing_after:  number;
    bearing_before: number;
    location:       number[];
    modifier?:      DrivingSide;
}

export enum Mode {
    Driving = "driving",
}

export interface Waypoint {
    distance: number;
    name:     string;
    location: number[];
}
